defaults: &defaults
  facebook:
    api_key: "516688585185934"
    api_secret: "9d4f94d4a3cdc1df4197a66e17ff3a7a"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  facebook:
    api_key: "516688585185934"
    api_secret: "9d4f94d4a3cdc1df4197a66e17ff3a7a"
